### ISSUE TITLE
Request: upload MDBM_File to cpan

### ISSUE THREAD

**Issue by skaji** [yahoo/mdbm#33]
Hi,
It's very nice if we can install the perl mdbm binding MDBM_File from cpan.
So could you upload MDBM_File to cpan?

I tried preparing a [repository](https://github.com/shoichikaji/perl-mdbm-install) so that we can install MDBM_File via:

```
$ cpanm git://github.com/shoichikaji/perl-mdbm-install.git
```

**Comment by timrc-git** [comment]
Hi Shoichi-

I had started work on this, and even registered a PAUSE account.
However, I was trying to make sure that we didn't trample on
MDBM libraries that were installed via other means (yum/apt/etc).

I'm currently looking at "alien" perl packages (one of the alternatives
recommended on perl IRC), but haven't had time to get it wrapped
up yet.

Thanks!

.timrc

**Comment by shoichikaji** [comment]
I'm very pleased to hear that you had started working on this!
Oh, you intend to prepare Alien::MDBM, and MDBM_File depends on it, right?
That sounds great.
I'm looking forward to MDBM_File being installable from cpan!
